openapi: 3.0.1
info:
  title: Code Generation Plugin
  description: A plugin that allows the user to generate code using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /generate-code:
    post:
      operationId: generateCode
      summary: Generate code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/generateCodeRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generateCodeResponse'

components:
  schemas:
    generateCodeRequest:
      type: object
      required:
      - prompt
      properties:
        prompt:
          type: string
          description: The prompt for the code generation.
          required: true
    generateCodeResponse:
      type: object
      properties:
        code:
          type: string
          description: The generated code.
          required: true

