openapi: 3.0.1
info:
  title: Reactor
  description: A plugin that renders React code into a webpage and returns a screenshot.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /render-code:
    post:
      operationId: renderCode
      summary: Render code into a webpage and return a screenshot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/renderCodeRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/renderCodeResponse'
components:
  schemas:
    renderCodeRequest:
      type: object
      required:
      - code
      properties:
        code:
          type: string
          description: The React code to render.
    renderCodeResponse:
      type: object
      properties:
        screenshot_url:
          type: string
          description: URL of the screenshot of the rendered code.
